spring:
  jpa:
    open-in-view: false
  profiles:
    include: core

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    password:
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/seed/data.sql
---
spring:
  config:
    activate:
      on-profile: prod